spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/symall?characterEncoding=utf-8
      username: root
      password: swd19980726
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.sjtu.symall.entity


logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error

